backend:
  name: github
  repo: alexrozov/digital-insight
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "slug", label: "Slug", widget: "string", hint: "Custom URL slug (leave empty to auto-generate)" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "excerpt", label: "Excerpt", widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "cases"
    label: "Cases"
    folder: "content/cases"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "slug", label: "Slug", widget: "string", hint: "Custom URL slug (leave empty to auto-generate)" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "excerpt", label: "Excerpt", widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "guides"
    label: "Guides"
    folder: "content/guides"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "slug", label: "Slug", widget: "string", hint: "Custom URL slug (leave empty to auto-generate)" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "excerpt", label: "Excerpt", widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "resources"
    label: "Resources"
    folder: "content/resources"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "slug", label: "Slug", widget: "string", hint: "Custom URL slug (leave empty to auto-generate)" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "excerpt", label: "Excerpt", widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
